language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - pip install coveralls
    - pip install coverage
    - pip install pytest-cov
script:
    - py.test --cov=arpeggio tests/unit
    - cat .coverage
after_success:
    - coveralls

