language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - python setup.py install
    - pip install python-coveralls
    - pip install pytest-cov
script:
    - py.test --cov=arpeggio --cov-report term-missing tests/unit
after_success:
    - coveralls

